Repository CPS-IT/typo3-project-template, pull requests merged in 2022-12, with the labels that each got.

#1 [BUGFIX] Require cpsit/project-builder ^1.0
  composer.json
  composer.lock
Labels: bug

#2 [BUGFIX] Exclude `.php-cs-fixer.cache` file in new projects
  templates/src/.gitignore.twig
Labels: bug

#3 [BUGFIX] Add `armin/editorconfig-cli` to `composer.json` template
  templates/src/composer.json.twig
Labels: bug

#4 [BUGFIX] Use correct syntax to find package paths for PHPStan analyze
  templates/src/composer.json.twig
Labels: bug

#5 [FEATURE] Include TYPO3 testing framework in project template
  templates/src/.gitignore.twig
  templates/src/composer.json.twig
  templates/src/deploy.php
  templates/src/phpunit.xml
Labels: enhancement

#6 [BUGFIX] Re-enable commented opcache clear in deploy.php template
  templates/src/deploy.php
Labels: bug

#9 [BUGFIX] Remove superfluous `allow-plugins` configuration
  composer.json
Labels: bug

#10 [BUGFIX] Provide default value for DDEV database version
  config.yaml
Labels: bug

#14 [TASK] Use TYPO3's default preset for core extensions
  templates/src/composer.json.twig
Labels: maintenance
